#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Change this directory to home
export HOME=$DIR

# Add local bin
export PATH=$DIR/root/bin/:$PATH

# Path to servers
SERVER=torus.cs.berkeley.edu
PROJ_PATH=$1

function send-usage {
  echo "Usage: send -f FILE -i ID"
}

function send {
  OPTIND=1
  ID=
  FILE=
  while getopts "f:i:h" O; do
    case $O in
      f)
        FILE=$OPTARG
        ;;
      i)
        ID=$OPTARG
        ;;
      h)
        send-usage; return
        ;;
      ?)
        send-usage; return 1
        ;;
    esac
  done

  if [ -z $FILE ] || [ -z $ID ]; then
    send-usage; return 1
  fi

  if [ -z $PROJ_PATH ]; then
    echo Error: No PROJ_PATH set.; return 1
  fi

  ADDRESS=cs164-$ID@$SERVER
  scp -r $FILE $ADDRESS:$PROJ_PATH
}

function connect {
  if [ -z $1 ]; then
    echo "Usage: connect ID"; return 1
  fi
  ssh cs164-$1@$SERVER
}
