# autograder: simple left comparator
print "one" < "three"
print "three" < "one"
print "one" < "one and a half" < "three"
print "one" < "nothing" < "seven"
print "one" < "one and a half" < "one"

print "one" > "three"
print "three" > "one"
print "one" > "one and a half" > "three"
print "one" > "nothing" > "seven"
print "one" > "one and a half" > "one"

print "one" <= "three"
print "three" <= "one"
print "one" <= "one and a half" <= "three"
print "one" <= "nothing" <= "seven"
print "one" <= "one and a half" <= "one"

print "one" >= "three"
print "three" >= "one"
print "one" >= "one and a half" >= "three"
print "one" >= "nothing" >= "seven"
print "one" >= "one and a half" >= "one"

print "one" == "one"
print "three" == "one"
print "one" == "one" == "one"
print "one" == "nothing" == "nothing"
print "one" == "one" == "nothing"

print "one" != "one"
print "three" != "one"
print "one" != "one" != "one"
print "one" != "nothing" != "nothing"
print "one" != "one" != "nothing"
