#line 2 "apyc-lexer.cc"

#line 4 "apyc-lexer.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 91
#define YY_END_OF_BUFFER 92
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[498] =
    {   0,
       85,   85,    0,    0,   92,   88,   85,   86,   86,   88,
       73,   85,   72,   69,   73,   63,   64,   69,   69,   69,
       79,   79,   69,   69,   69,   69,   88,   71,   71,   65,
       88,   66,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   67,   68,
       90,   84,   89,   83,   83,   83,   83,   83,   85,   85,
       86,    1,   73,   75,    0,   85,   72,   73,   75,    0,
        2,    3,    4,   79,   81,   80,   79,    5,    6,    7,
        8,    9,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   71,    0,    0,   87,

       87,   71,   70,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   52,   71,   53,   54,   71,   71,
       71,   57,   58,   71,   71,   71,   71,   71,   71,   71,
       71,   83,   83,   83,   83,   83,   82,   82,    0,    0,
        0,   75,   74,   73,   73,   74,   73,   73,   79,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   77,    0,
        0,   77,    0,   87,   44,   71,   71,   71,   71,   48,
       70,   71,   71,   71,   71,   71,   51,   71,   71,   71,

       71,   71,   71,   56,   71,   71,   71,   71,   71,   71,
       71,   74,    0,    0,   74,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   20,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   77,    0,    0,    0,
        0,    0,    0,   71,   71,   71,   71,   49,   50,   71,
       71,   71,   71,   71,   71,   71,   59,   71,   71,   71,
       71,   71,   74,    0,    0,   74,   74,    0,    0,   74,
        0,    0,    0,    0,    0,    0,    0,   17,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   30,

        0,    0,    0,    0,    0,    0,   38,   43,    0,    0,
        0,    0,    0,    0,   71,   45,   46,   71,   71,   71,
       71,   71,   71,   71,   71,   60,   71,   62,   76,   74,
       74,   74,   74,    0,    0,    0,    0,    0,   15,   16,
       18,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   31,    0,    0,    0,    0,   37,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   71,   71,   55,
       61,   74,   74,   10,    0,    0,   13,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   29,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   78,    0,    0,

        0,    0,   71,    0,    0,    0,   19,    0,    0,    0,
        0,   25,    0,    0,    0,   32,   33,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   47,   11,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   41,   42,    0,    0,    0,   22,    0,    0,
        0,    0,    0,   34,    0,    0,    0,   40,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   26,    0,    0,    0,   36,    0,
        0,   14,   21,   23,    0,   27,   28,   35,    0,   12,
       24,    0,    0,    0,    0,   39,    0

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    8,    9,    1,   10,   11,
       12,   13,    9,    9,   14,    9,   15,   16,   17,   17,
       17,   17,   17,   17,   17,   18,   18,   19,    9,   20,
       21,   22,    1,   23,   24,   24,   24,   24,   24,   24,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   26,   25,   25,   25,   25,   25,   27,   25,   25,
       28,   29,   30,    1,   31,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   25,   41,   42,   43,   44,
       45,   46,   25,   47,   48,   49,   50,   51,   52,   53,
       54,   25,   55,    1,   56,    1,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,

       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   58
    } ;

static yyconst flex_int32_t yy_meta[60] =
    {   0,
        1,    1,    2,    2,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    3,    3,    1,    1,
        1,    1,    1,    3,    4,    4,    4,    1,    1,    1,
        4,    3,    3,    3,    3,    3,    3,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    1,    1,    1,    5,    5
    } ;

static yyconst flex_int16_t yy_base[523] =
    {   0,
        0,    0,    0,   58,  694,  695,   61,  695,  690,  671,
       58,    0,    0,  695,   56,  695,  695,  678,  668,  674,
       53,   56,  669,  666,  665,   54,   84,    0,   71,  695,
       75,  695,   38,  638,   46,  648,   41,   50,  641,   55,
      650,   57,   64,   61,   99,  634,   73,  640,  695,  695,
      695,  695,  695,  695,  134,    0,  676,  111,  121,    0,
      695,  695,  116,  672,  673,    0,    0,  100,  666,  671,
      695,  695,  695,  126,  130,    0,  133,  695,  695,  695,
      695,  695,   92,  104,  114,  123,  121,  621,  113,  122,
      124,  628,  130,  125,  137,  628,    0,  164,  161,  669,

      170,  635,  621,  632,  635,  622,  139,   56,  144,  621,
      617,  618,  613,  616,    0,  614,    0,    0,  616,  609,
      608,    0,    0,  608,  615,  614,  604,  598,  611,  601,
      613,  695,  181,    0,  645,  191,  695,    0,  193,    0,
      644,  695,  173,  176,  183,  182,  188,  196,    0,  604,
      158,  597,  595,  599,  597,  599,  608,  596,  601,  603,
      590,  588,  590,  602,  583,  594,  582,  594,  588,  587,
      586,  582,  591,  576,  576,  575,  575,  195,  613,  614,
      193,  607,  612,  613,    0,  578,  581,  564,  562,    0,
        0,  573,  573,  572,  573,  574,    0,  562,  554,  570,

      557,  568,  560,    0,  551,  554,  549,  546,  553,  555,
      551,  198,  201,  588,  199,  200,  587,  545,  549,  555,
      547,  539,  540,  550,  541,  534,  535,  695,  531,  532,
      535,  543,  540,  544,  525,  524,  522,  524,  526,  535,
      519,  519,  528,  523,  528,  517,  695,  207,  208,  212,
      206,  209,  223,  515,  520,  512,  519,    0,    0,  512,
      515,  509,  523,  507,  518,  501,    0,  502,  514,  502,
      512,  512,  214,  215,  542,  228,  213,  222,  541,  236,
      510,  509,  494,  503,  500,  493,  497,  695,  489,  504,
      504,  503,  501,  483,  478,  488,  498,  497,  485,  695,

      477,  485,  493,  489,  486,  485,  214,  695,  234,  241,
      516,  238,  240,  515,  469,    0,    0,  473,  467,  473,
      478,  471,  463,  479,  474,    0,  465,    0,  695,  250,
      248,  252,  249,  467,  467,  472,  461,  471,  695,  695,
      695,  456,  467,  459,  458,  459,  452,  457,  462,  460,
      458,  451,  448,  449,  443,  440,  695,  224,  457,  254,
      258,  483,  265,  262,  263,  482,  279,  435,  430,    0,
        0,  268,  266,  695,  439,  435,  695,  431,  444,  439,
      438,  429,  431,  428,  425,  428,  432,  695,  427,  432,
      429,  428,  436,  421,  425,  432,  423,  695,  282,  274,

      283,  280,  426,  423,  420,  410,  695,  410,  409,  425,
      411,  695,  418,  410,  404,  695,  695,  403,  404,  407,
      401,  399,  399,  410,  278,  286,    0,  695,  398,  407,
      396,  392,  398,  408,  391,  391,  390,  386,  385,  393,
      389,  382,  695,  695,  381,  382,  386,  695,  387,  377,
      393,  392,  381,  695,  382,  373,  388,  695,  379,  382,
      385,  368,  361,  372,  366,  380,  324,  316,  295,  286,
      290,  260,  264,  264,  695,  270,  251,  260,  695,  254,
      257,  695,  695,  695,  264,  695,  695,  695,  268,  695,
      695,  256,  218,   91,   35,  695,  695,  315,  320,  325,

      329,  331,  335,  337,  341,  346,  351,  355,  359,   64,
      363,  367,  371,  375,  379,  383,  387,  391,  395,  399,
      403,  407
    } ;

static yyconst flex_int16_t yy_def[523] =
    {   0,
      497,    1,  498,  499,  497,  497,  497,  497,  497,  497,
      500,  501,  502,  497,  503,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  504,  504,  497,
      497,  497,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  497,  497,
      497,  497,  497,  497,  505,  506,  506,  507,  497,  501,
      497,  497,  500,  497,  508,  501,  502,  503,  497,  509,
      497,  497,  497,  497,  497,  510,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  504,  511,  512,  497,

      497,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  497,  505,  506,  506,  507,  497,  506,  507,  506,
      506,  497,  513,  500,  500,  514,  503,  503,  510,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  511,  497,  515,
      512,  497,  516,  497,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,

      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  513,  517,  513,  514,  518,  514,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  519,  511,  511,
      520,  512,  512,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  504,  504,
      504,  504,  513,  517,  517,  513,  514,  518,  518,  514,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,

      497,  497,  497,  497,  497,  497,  497,  497,  519,  521,
      519,  520,  522,  520,  504,  504,  504,  504,  504,  504,
      504,  504,  504,  504,  504,  504,  504,  504,  497,  513,
      513,  514,  514,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  519,
      521,  521,  519,  520,  522,  522,  520,  504,  504,  504,
      504,  513,  514,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  519,  519,

      520,  520,  504,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  519,  520,  504,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,    0,  497,  497,  497,

      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497
    } ;

static yyconst flex_int16_t yy_nxt[755] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   22,   23,   24,
       25,   26,   27,   28,   28,   29,   28,   30,   31,   32,
       28,   33,   34,   35,   36,   37,   38,   39,   28,   40,
       28,   41,   28,   42,   43,   44,   45,   28,   46,   28,
       28,   47,   28,   48,   49,   50,   51,   52,   51,   55,
       56,   57,   59,   64,   58,   69,  149,   60,   74,   74,
       75,   77,   77,   77,   81,   82,   98,  100,  101,   76,
       99,  102,  108,  496,   70,  103,   65,  105,  120,  110,
      106,  115,  124,  109,  111,  192,  112,  116,  117,  113,

      122,  121,  118,  193,   98,   76,   83,  125,   99,  142,
      123,  129,  130,  140,  141,   84,   85,   86,   87,   88,
       89,  142,   59,   90,  150,   91,   92,   60,   70,   93,
      126,   94,   95,   96,  127,  133,  134,  135,  495,  151,
      136,   74,   74,   75,   65,   75,   75,   75,   77,   77,
       77,  152,  153,  154,  156,  155,  159,  162,  164,  166,
      160,  169,  163,  167,  157,  165,  171,  158,  174,  179,
      182,  184,  100,  172,  173,  190,  170,  194,  213,  195,
      191,  142,  133,  134,  135,  144,  175,  136,  142,  183,
      176,  216,  180,  140,  141,  140,  141,  142,  147,  219,

      247,  214,  247,  213,   65,  142,  274,  220,  216,  278,
      217,   65,  310,  247,  249,  313,   70,  247,  247,  213,
      329,  183,  216,  180,   70,  252,  214,  217,  279,  275,
      331,  329,  247,  213,  314,  311,  180,  183,  333,  310,
      180,  217,  214,  275,  358,  216,  361,  313,  359,  365,
      279,  183,  372,  213,  373,  213,  214,  494,  216,  310,
      394,  216,  311,  398,  217,  395,  314,  400,  366,  362,
      310,  313,  398,  213,  396,  216,  214,  217,  214,  310,
      217,  402,  311,  310,  425,  426,  362,  310,  313,  313,
      314,  366,  313,  311,  217,  313,  214,  493,  492,  491,

      490,  489,  311,  488,  487,  486,  311,  314,  314,  485,
      311,  314,  484,  483,  314,   53,   53,   53,   53,   53,
       54,   54,   54,   54,   54,   63,  482,   63,   63,   66,
      481,   66,   66,   67,   67,   68,  480,   68,   68,   97,
       97,  132,  132,  132,  132,  132,  137,  137,  137,  137,
      137,  139,  139,  139,  139,  144,  144,  144,  144,  147,
      147,  147,  147,  178,  479,  178,  178,  181,  478,  181,
      181,  212,  212,  212,  212,  215,  215,  215,  215,  249,
      249,  249,  249,  252,  252,  252,  252,  273,  273,  273,
      273,  277,  277,  277,  277,  309,  309,  309,  309,  312,

      312,  312,  312,  360,  360,  360,  360,  364,  364,  364,
      364,  477,  476,  475,  474,  473,  472,  471,  470,  469,
      468,  467,  466,  465,  464,  463,  462,  461,  460,  459,
      458,  457,  456,  455,  454,  453,  452,  451,  450,  449,
      448,  447,  446,  445,  444,  443,  442,  441,  440,  439,
      438,  437,  436,  435,  434,  433,  432,  431,  430,  429,
      428,  427,  424,  423,  422,  421,  420,  419,  418,  417,
      416,  415,  414,  413,  412,  411,  410,  409,  408,  407,
      406,  405,  404,  191,  403,  401,  399,  397,  393,  392,
      391,  390,  389,  388,  387,  386,  385,  384,  383,  382,

      381,  380,  379,  378,  377,  376,  375,  374,  371,  370,
      191,  191,  191,  191,  369,  191,  368,  191,  367,  363,
      357,  356,  355,  354,  353,  352,  351,  350,  349,  348,
      347,  346,  345,  344,  343,  342,  341,  340,  339,  338,
      337,  336,  335,  334,  332,  330,  191,  328,  327,  191,
      326,  325,  324,  323,  322,  321,  320,  319,  318,  317,
      316,  315,  308,  307,  306,  305,  304,  303,  302,  301,
      300,  299,  298,  297,  296,  295,  294,  293,  292,  291,
      290,  289,  288,  287,  286,  285,  284,  283,  282,  281,
      280,  276,  272,  191,  271,  270,  269,  268,  267,  266,

      265,  264,  263,  262,  191,  261,  191,  260,  259,  258,
      257,  256,  255,  254,  184,  253,  251,  250,  248,  246,
      245,  244,  243,  242,  241,  240,  239,  238,  237,  236,
      235,  234,  233,  232,  231,  230,  229,  228,  227,  226,
      225,  224,  223,  222,  221,  218,  138,  138,  211,  210,
      209,  191,  208,  207,  206,  205,  204,  203,  202,  201,
      200,  199,  198,  197,  196,  189,  188,  187,  186,  185,
      184,  177,  168,  161,  148,  146,  145,  143,  138,  131,
      128,  119,  114,  107,  104,   80,   79,   78,   73,   72,
       71,   62,   61,  497,    5,  497,  497,  497,  497,  497,

      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497
    } ;

static yyconst flex_int16_t yy_chk[755] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    4,
        4,    4,    7,   11,    4,   15,  510,    7,   21,   21,
       21,   22,   22,   22,   26,   26,   29,   31,   31,   21,
       29,   33,   37,  495,   15,   33,   11,   35,   42,   38,
       35,   40,   44,   37,   38,  108,   38,   40,   40,   38,

       43,   42,   40,  108,   45,   21,   27,   44,   45,   68,
       43,   47,   47,   58,   58,   27,   27,   27,   27,   27,
       27,   63,   59,   27,   83,   27,   27,   59,   68,   27,
       45,   27,   27,   27,   45,   55,   55,   55,  494,   83,
       55,   74,   74,   74,   63,   75,   75,   75,   77,   77,
       77,   84,   84,   85,   86,   85,   87,   89,   90,   91,
       87,   93,   89,   91,   86,   90,   94,   86,   95,   98,
       99,  101,  101,   94,   94,  107,   93,  109,  143,  109,
      107,  144,  133,  133,  133,  145,   95,  133,  145,   99,
       95,  146,   98,  136,  136,  139,  139,  147,  148,  151,

      178,  143,  181,  212,  144,  148,  213,  151,  215,  216,
      146,  145,  248,  249,  250,  251,  147,  250,  252,  273,
      274,  181,  277,  178,  148,  253,  212,  215,  216,  213,
      276,  278,  253,  276,  251,  248,  249,  252,  280,  309,
      250,  277,  273,  274,  307,  280,  310,  312,  307,  313,
      278,  253,  330,  331,  332,  330,  276,  493,  333,  360,
      358,  332,  309,  361,  280,  358,  312,  363,  313,  310,
      363,  364,  365,  372,  358,  373,  331,  333,  330,  400,
      332,  367,  360,  425,  399,  401,  361,  399,  367,  402,
      364,  365,  401,  363,  373,  426,  372,  492,  489,  485,

      481,  480,  400,  478,  477,  476,  425,  367,  402,  474,
      399,  401,  473,  472,  426,  498,  498,  498,  498,  498,
      499,  499,  499,  499,  499,  500,  471,  500,  500,  501,
      470,  501,  501,  502,  502,  503,  469,  503,  503,  504,
      504,  505,  505,  505,  505,  505,  506,  506,  506,  506,
      506,  507,  507,  507,  507,  508,  508,  508,  508,  509,
      509,  509,  509,  511,  468,  511,  511,  512,  467,  512,
      512,  513,  513,  513,  513,  514,  514,  514,  514,  515,
      515,  515,  515,  516,  516,  516,  516,  517,  517,  517,
      517,  518,  518,  518,  518,  519,  519,  519,  519,  520,

      520,  520,  520,  521,  521,  521,  521,  522,  522,  522,
      522,  466,  465,  464,  463,  462,  461,  460,  459,  457,
      456,  455,  453,  452,  451,  450,  449,  447,  446,  445,
      442,  441,  440,  439,  438,  437,  436,  435,  434,  433,
      432,  431,  430,  429,  424,  423,  422,  421,  420,  419,
      418,  415,  414,  413,  411,  410,  409,  408,  406,  405,
      404,  403,  397,  396,  395,  394,  393,  392,  391,  390,
      389,  387,  386,  385,  384,  383,  382,  381,  380,  379,
      378,  376,  375,  369,  368,  366,  362,  359,  356,  355,
      354,  353,  352,  351,  350,  349,  348,  347,  346,  345,

      344,  343,  342,  338,  337,  336,  335,  334,  327,  325,
      324,  323,  322,  321,  320,  319,  318,  315,  314,  311,
      306,  305,  304,  303,  302,  301,  299,  298,  297,  296,
      295,  294,  293,  292,  291,  290,  289,  287,  286,  285,
      284,  283,  282,  281,  279,  275,  272,  271,  270,  269,
      268,  266,  265,  264,  263,  262,  261,  260,  257,  256,
      255,  254,  246,  245,  244,  243,  242,  241,  240,  239,
      238,  237,  236,  235,  234,  233,  232,  231,  230,  229,
      227,  226,  225,  224,  223,  222,  221,  220,  219,  218,
      217,  214,  211,  210,  209,  208,  207,  206,  205,  203,

      202,  201,  200,  199,  198,  196,  195,  194,  193,  192,
      189,  188,  187,  186,  184,  183,  182,  180,  179,  177,
      176,  175,  174,  173,  172,  171,  170,  169,  168,  167,
      166,  165,  164,  163,  162,  161,  160,  159,  158,  157,
      156,  155,  154,  153,  152,  150,  141,  135,  131,  130,
      129,  128,  127,  126,  125,  124,  121,  120,  119,  116,
      114,  113,  112,  111,  110,  106,  105,  104,  103,  102,
      100,   96,   92,   88,   70,   69,   65,   64,   57,   48,
       46,   41,   39,   36,   34,   25,   24,   23,   20,   19,
       18,   10,    9,    5,  497,  497,  497,  497,  497,  497,

      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497,  497,  497,  497,  497,  497,  497,
      497,  497,  497,  497
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "apyc-lexer.l"
/* Generated from apyc.hn at Fri Nov 15 10:36:26 2013 GMT. */
#define YY_NO_INPUT 1
#line 6 "apyc-lexer.l"
#define YY_LEXER_1
#include "horn-parse-lex.cc"

/* Lexical Rules */
#line 798 "apyc-lexer.cc"

#define INITIAL 0
#define YYPREFERRED 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 71 "apyc-lexer.l"


#line 985 "apyc-lexer.cc"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 498 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 695 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 73 "apyc-lexer.l"
{ { YY_LEXLHS(_TOK_4); YYLEXRET; } } 
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 74 "apyc-lexer.l"
{ { YY_LEXLHS(POW); YYLEXRET; } } 
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 75 "apyc-lexer.l"
{ { YY_LEXLHS(_TOK_15); YYLEXRET; } } 
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 76 "apyc-lexer.l"
{ { YY_LEXLHS(DIVDIV); YYLEXRET; } } 
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 77 "apyc-lexer.l"
{ { YY_LEXLHS(_TOK_14); YYLEXRET; } } 
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 78 "apyc-lexer.l"
{ { YY_LEXLHS(_TOK_2); YYLEXRET; } } 
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 79 "apyc-lexer.l"
{ { YY_LEXLHS(_TOK_1); YYLEXRET; } } 
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 80 "apyc-lexer.l"
{ { YY_LEXLHS(_TOK_3); YYLEXRET; } } 
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 81 "apyc-lexer.l"
{ { YY_LEXLHS(_TOK_9); YYLEXRET; } } 
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 82 "apyc-lexer.l"
{ { YY_LEXLHS(CLASS_BLOCK); YYLEXRET; } } 
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 83 "apyc-lexer.l"
{ { YY_LEXLHS(SLICING_TARGET); YYLEXRET; } } 
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 84 "apyc-lexer.l"
{ { YY_LEXLHS(SUBSCRIPTION_TARGET); YYLEXRET; } } 
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 85 "apyc-lexer.l"
{ { YY_LEXLHS(ASSIGN); YYLEXRET; } } 
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 86 "apyc-lexer.l"
{ { YY_LEXLHS(ATTRIBUTEREF); YYLEXRET; } } 
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 87 "apyc-lexer.l"
{ { YY_LEXLHS(BINOP); YYLEXRET; } } 
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 88 "apyc-lexer.l"
{ { YY_LEXLHS(BLOCK); YYLEXRET; } } 
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 89 "apyc-lexer.l"
{ { YY_LEXLHS(CALL); YYLEXRET; } } 
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 90 "apyc-lexer.l"
{ { YY_LEXLHS(CLASS); YYLEXRET; } } 
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 91 "apyc-lexer.l"
{ { YY_LEXLHS(COMPARE); YYLEXRET; } } 
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 92 "apyc-lexer.l"
{ { YY_LEXLHS(METHOD); YYLEXRET; } } 
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 93 "apyc-lexer.l"
{ { YY_LEXLHS(DICT_DISPLAY); YYLEXRET; } } 
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 94 "apyc-lexer.l"
{ { YY_LEXLHS(EXPR_LIST); YYLEXRET; } } 
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 95 "apyc-lexer.l"
{ { YY_LEXLHS(FORMALS_LIST); YYLEXRET; } } 
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 96 "apyc-lexer.l"
{ { YY_LEXLHS(FUNCTION_TYPE); YYLEXRET; } } 
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 97 "apyc-lexer.l"
{ { YY_LEXLHS(IF_EXPR); YYLEXRET; } } 
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 98 "apyc-lexer.l"
{ { YY_LEXLHS(INT_LITERAL); YYLEXRET; } } 
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 99 "apyc-lexer.l"
{ { YY_LEXLHS(LEFT_COMPARE); YYLEXRET; } } 
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 100 "apyc-lexer.l"
{ { YY_LEXLHS(LIST_DISPLAY); YYLEXRET; } } 
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 101 "apyc-lexer.l"
{ { YY_LEXLHS(MODULE); YYLEXRET; } } 
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 102 "apyc-lexer.l"
{ { YY_LEXLHS(PAIR); YYLEXRET; } } 
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 103 "apyc-lexer.l"
{ { YY_LEXLHS(PRINT); YYLEXRET; } } 
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 104 "apyc-lexer.l"
{ { YY_LEXLHS(PRINTLN); YYLEXRET; } } 
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 105 "apyc-lexer.l"
{ { YY_LEXLHS(SLICING); YYLEXRET; } } 
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 106 "apyc-lexer.l"
{ { YY_LEXLHS(STMT_LIST); YYLEXRET; } } 
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 107 "apyc-lexer.l"
{ { YY_LEXLHS(SUBSCRIPTION); YYLEXRET; } } 
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 108 "apyc-lexer.l"
{ { YY_LEXLHS(TARGET_LIST); YYLEXRET; } } 
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 109 "apyc-lexer.l"
{ { YY_LEXLHS(TUPLE); YYLEXRET; } } 
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 110 "apyc-lexer.l"
{ { YY_LEXLHS(TYPE); YYLEXRET; } } 
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 111 "apyc-lexer.l"
{ { YY_LEXLHS(TYPE_FORMALS_LIST); YYLEXRET; } } 
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 112 "apyc-lexer.l"
{ { YY_LEXLHS(TYPE_LIST); YYLEXRET; } } 
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 113 "apyc-lexer.l"
{ { YY_LEXLHS(TYPE_VAR); YYLEXRET; } } 
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 114 "apyc-lexer.l"
{ { YY_LEXLHS(TYPED_ID); YYLEXRET; } } 
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 115 "apyc-lexer.l"
{ { YY_LEXLHS(UNOP); YYLEXRET; } } 
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 116 "apyc-lexer.l"
{ { YY_LEXLHS(AND); YYLEXRET; } } 
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 117 "apyc-lexer.l"
{ { YY_LEXLHS(BREAK); YYLEXRET; } } 
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 118 "apyc-lexer.l"
{ { YY_LEXLHS(_TOK_12); YYLEXRET; } } 
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 119 "apyc-lexer.l"
{ { YY_LEXLHS(CONTINUE); YYLEXRET; } } 
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 120 "apyc-lexer.l"
{ { YY_LEXLHS(DEF); YYLEXRET; } } 
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 121 "apyc-lexer.l"
{ { YY_LEXLHS(_TOK_11); YYLEXRET; } } 
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 122 "apyc-lexer.l"
{ { YY_LEXLHS(_TOK_0); YYLEXRET; } } 
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 123 "apyc-lexer.l"
{ { YY_LEXLHS(FOR); YYLEXRET; } } 
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 124 "apyc-lexer.l"
{ { YY_LEXLHS(IF); YYLEXRET; } } 
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 125 "apyc-lexer.l"
{ { YY_LEXLHS(_TOK_6); YYLEXRET; } } 
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 126 "apyc-lexer.l"
{ { YY_LEXLHS(_TOK_5); YYLEXRET; } } 
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 127 "apyc-lexer.l"
{ { YY_LEXLHS(NATIVE); YYLEXRET; } } 
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 128 "apyc-lexer.l"
{ { YY_LEXLHS(NOT); YYLEXRET; } } 
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 129 "apyc-lexer.l"
{ { YY_LEXLHS(_TOK_13); YYLEXRET; } } 
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 130 "apyc-lexer.l"
{ { YY_LEXLHS(OR); YYLEXRET; } } 
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 131 "apyc-lexer.l"
{ { YY_LEXLHS(_TOK_7); YYLEXRET; } } 
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 132 "apyc-lexer.l"
{ { YY_LEXLHS(_TOK_8); YYLEXRET; } } 
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 133 "apyc-lexer.l"
{ { YY_LEXLHS(_TOK_10); YYLEXRET; } } 
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 134 "apyc-lexer.l"
{ { YY_LEXLHS(WHILE); YYLEXRET; } } 
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 135 "apyc-lexer.l"
{ { YY_LEXLHS('(');incr (bracket_depth); YYLEXRET; } } 
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 136 "apyc-lexer.l"
{ { YY_LEXLHS(')');decr (bracket_depth); YYLEXRET; } } 
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 137 "apyc-lexer.l"
{ { YY_LEXLHS('[');incr (bracket_depth); YYLEXRET; } } 
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 138 "apyc-lexer.l"
{ { YY_LEXLHS(']');decr (bracket_depth); YYLEXRET; } } 
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 139 "apyc-lexer.l"
{ { YY_LEXLHS('{');incr (bracket_depth); YYLEXRET; } } 
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 140 "apyc-lexer.l"
{ { YY_LEXLHS('}');decr (bracket_depth); YYLEXRET; } } 
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 141 "apyc-lexer.l"
{ { YYSIMPLELEXRET; } } 
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 142 "apyc-lexer.l"
{ { YY_LEXLHS; error (yysource_location (),
                         "The '%s' symbol is not part of our subset",
                         yylhs.text ()); YYLEXRET; } } 
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 145 "apyc-lexer.l"
{ { YY_LEXLHS(ID); YYLEXRET; } } 
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 146 "apyc-lexer.l"
{ { YY_LEXLHS(TYPE_VAR); YYLEXRET; } } 
	YY_BREAK
case 73:
/* rule 73 can match eol */
YY_RULE_SETUP
#line 147 "apyc-lexer.l"
{ { YY_LEXLHS; error (yysource_location (), "unterminated string"); YYLEXRET; } } 
	YY_BREAK
case 74:
/* rule 74 can match eol */
YY_RULE_SETUP
#line 148 "apyc-lexer.l"
{ { YY_LEXLHS; error (yysource_location (), "unterminated long string"); YYLEXRET; } } 
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 149 "apyc-lexer.l"
{ { YY_LEXLHS(STRING);yylhs = AST::make_token (STRING, yylhs.text_size ()-2, yylhs.text ()+1); YYLEXRET; } } 
	YY_BREAK
case 76:
/* rule 76 can match eol */
YY_RULE_SETUP
#line 150 "apyc-lexer.l"
{ { YY_LEXLHS(STRING);yylhs = AST::make_token (STRING, yylhs.text_size ()-6, yylhs.text ()+3); YYLEXRET; } } 
	YY_BREAK
case 77:
/* rule 77 can match eol */
YY_RULE_SETUP
#line 151 "apyc-lexer.l"
{ { YY_LEXLHS(RAWSTRING);yylhs = AST::make_token (RAWSTRING, yylhs.text_size ()-3, yylhs.text ()+2); YYLEXRET; } } 
	YY_BREAK
case 78:
/* rule 78 can match eol */
YY_RULE_SETUP
#line 152 "apyc-lexer.l"
{ { YY_LEXLHS(RAWSTRING);yylhs = AST::make_token (RAWSTRING, yylhs.text_size ()-7, yylhs.text ()+4); YYLEXRET; } } 
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 153 "apyc-lexer.l"
{ { YY_LEXLHS(INT_LITERAL);check_numeral (yylhs.text ()); YYLEXRET; } } 
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 154 "apyc-lexer.l"
{ { YY_LEXLHS;  YYLEXRET; } } 
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 155 "apyc-lexer.l"
{ { YY_LEXLHS; error (yysource_location (), "invalid numeral"); YYLEXRET; } } 
	YY_BREAK
case 82:
/* rule 82 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 156 "apyc-lexer.l"
{ { YY_LEXLHS;  YYLEXRET; } } 
	YY_BREAK
case 83:
/* rule 83 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 157 "apyc-lexer.l"
{ { YY_LEXLHS; YYSET_TOKEN (do_indent(yylhs.text ())); YYLEXRET; } } 
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 158 "apyc-lexer.l"
{ { YY_LEXLHS; int tok = do_indent ("");
                  yyleng=1;  /* KLUDGE to fix bug. */
                  if (pop_source_file () || tok > 0)
                      YYSET_TOKEN (tok);
                  else
                      YYSET_TOKEN (0); YYLEXRET; } } 
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 164 "apyc-lexer.l"
{ { YY_LEXLHS;  YYLEXRET; } } 
	YY_BREAK
case 86:
/* rule 86 can match eol */
YY_RULE_SETUP
#line 165 "apyc-lexer.l"
{ { YY_LEXLHS(NEWLINE);if (bracket_depth > 0) {
                      yy_set_bol (0);
                      YYIGNORE;
                  } YYLEXRET; } } 
	YY_BREAK
case 87:
/* rule 87 can match eol */
YY_RULE_SETUP
#line 169 "apyc-lexer.l"
{ { YY_LEXLHS; yy_set_bol (0); YYLEXRET; } } 
	YY_BREAK
case 88:
/* rule 88 can match eol */
YY_RULE_SETUP
#line 170 "apyc-lexer.l"
{ { YY_LEXLHS; error (yysource_location (), "invalid character"); YYLEXRET; } } 
	YY_BREAK
case 89:
/* rule 89 can match eol */
YY_RULE_SETUP
#line 173 "apyc-lexer.l"
{ yyless(0); return -1; }
	YY_BREAK
case 90:
/* rule 90 can match eol */
YY_RULE_SETUP
#line 174 "apyc-lexer.l"
{ if (yytext[0] == YYEOF_CHAR) {
                         yyless (0);     
                         return YYEOF;
                     }
                     return yytext[0]; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 180 "apyc-lexer.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1557 "apyc-lexer.cc"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(YYPREFERRED):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 59);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 498 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 59;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 498 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 497);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 180 "apyc-lexer.l"



#define YY_LEXER_2
#include "horn-parse-lex.cc"

