print "HELLO WORLD"
print "testing"
print " <(:)"
print "\'\'"
print "a" + "b"
print "an apple " "is a tree"
print "wenson " "makes strange tests, " "and is not human"
print "God once said \'" "\"\"\'" + " (:)> "
print """hello
world"""
print R"HELLO WORLD"
print r"tes\ti\ng"
print R" <(:)"
print r"\'\'"
print R"a" + "b"
print r"an app\le " R"is\ a tree"
print r"wenson " R"makes s\trange tests, " "and \is n\ot human"
print r"God once said \'" "\"\"\'" + " (:)> "
print R"""hello
world"""
print r"hello" + "world" R"this" + "is another" + R"string" + r"test"
